import { z } from 'zod';

export const BookingSchema = z.object({
    id: z.string(),
    customer_name: z.string(),
    customer_phone: z.string(),
    customer_email: z.string().email().nullable().optional().or(z.literal('')),
    booking_date: z.string(),
    booking_time: z.string(),
    party_size: z.number().positive(),
    status: z.enum(['requested', 'pending', 'confirmed', 'rejected', 'completed', 'cancelled', 'no_show']),
    special_requests: z.string().nullable().optional(),
    occasion: z.string().nullable().optional(),
    dietary_requirements: z.string().nullable().optional(),
    duration_minutes: z.number().nullable().optional(),
    notes: z.string().nullable().optional(),
    source: z.string().nullable().optional(),
    confirmation_code: z.string().nullable().optional(),
    confirmed_at: z.string().nullable().optional(),
    cancelled_at: z.string().nullable().optional(),
    cancellation_reason: z.string().nullable().optional(),
    checked_in_at: z.string().nullable().optional(),
    completed_at: z.string().nullable().optional(),
    google_calendar_event_id: z.string().nullable().optional(),
    confirmation_sent: z.boolean().nullable().optional(),
    reminder_sent: z.boolean().nullable().optional(),
    estimated_revenue: z.union([z.number(), z.string()]).nullable().optional(),
    actual_revenue: z.union([z.number(), z.string()]).nullable().optional(),
    metadata: z.record(z.string(), z.any()).nullable().optional(),
    agent: z.string().nullable().optional(),
    customer: z.string().nullable().optional(),
    customer_name_display: z.string().nullable().optional(),
    is_upcoming: z.boolean().nullable().optional(),
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
});

export const BookingAnalyticsSchema = z.object({
    total_bookings: z.number(),
    confirmed: z.number(),
    completed: z.number(),
    cancelled: z.number(),
    no_shows: z.number(),
    pending: z.number(),
    avg_party_size: z.number(),
    total_revenue: z.number(),
    by_source: z.record(z.string(), z.number()),
    daily_trend: z.array(z.object({ date: z.string(), count: z.number() })).optional(),
    hourly_distribution: z.record(z.string(), z.number()).optional(),
    conversion_rate: z.number().optional(),
});
