import { z } from 'zod';

export const CustomerSchema = z.object({
    id: z.string(),
    name: z.string(),
    phone_number: z.string(),
    email: z.string().email().nullable().optional().or(z.literal('')),
    alternate_phone: z.string().nullable().optional(),
    avatar: z.string().nullable().optional(),
    language_preference: z.string().nullable().optional(),
    special_requests: z.string().nullable().optional(),
    dietary_restrictions: z.array(z.any()).nullable().optional(),
    total_bookings: z.number().default(0),
    completed_bookings: z.number().default(0),
    cancelled_bookings: z.number().default(0),
    no_shows: z.number().default(0),
    total_calls: z.number().default(0),
    total_spent: z.union([z.number(), z.string()]).default(0),
    lifetime_value: z.union([z.number(), z.string()]).default(0),
    average_party_size: z.number().default(0),
    first_visit_date: z.string().nullable().optional(),
    last_visit_date: z.string().nullable().optional(),
    is_vip: z.boolean().default(false),
    is_blacklisted: z.boolean().default(false),
    blacklist_reason: z.string().nullable().optional(),
    is_repeat_customer: z.boolean().nullable().optional(),
    status: z.enum(['active', 'new', 'vip', 'inactive']).nullable().optional(),
    satisfaction: z.number().nullable().optional(),
    preferred_time: z.string().nullable().optional(),
    favorite_service: z.string().nullable().optional(),
    ai_summary: z.string().nullable().optional(),
    insights: z.array(z.string()).nullable().optional(),
    notes: z.string().nullable().optional(),
    tags: z.array(z.string()).nullable().optional(),
    preferences: z.record(z.string(), z.any()).nullable().optional(),
    created_at: z.string(),
    updated_at: z.string(),
});

export const CustomerBehaviorSchema = z.object({
    conversion_rate: z.number().default(0),
    cancellation_rate: z.number().default(0),
    no_show_rate: z.number().default(0),
    preferred_time: z.string().nullable().optional(),
    preferred_language: z.string().nullable().optional(),
    sentiment_trend: z.enum(['improving', 'stable', 'declining']).nullable().optional().default('stable'),
    avg_sentiment: z.number().nullable().optional(),
    requires_strict_confirmation: z.boolean().default(false),
    prefers_fast_flow: z.boolean().default(false),
    has_price_sensitivity: z.boolean().nullable().optional(),
    ai_notes: z.string().nullable().optional(),
    last_analyzed: z.string().nullable().optional(),
});

export const CustomerInsightsSchema = z.object({
    customer: z.object({
        id: z.string(),
        name: z.string(),
        phone: z.string(),
        email: z.string().email().nullable().optional().or(z.literal('')),
        is_vip: z.boolean().default(false),
        is_repeat: z.boolean().default(false),
        lifetime_value: z.number().default(0),
        first_visit: z.string().nullable().optional(),
        last_visit: z.string().nullable().optional(),
    }),
    behavior: CustomerBehaviorSchema.optional(),
    call_summary: z.object({
        total_calls: z.number().default(0),
        positive_calls: z.number().default(0),
        neutral_calls: z.number().default(0),
        negative_calls: z.number().default(0),
        avg_duration: z.number().default(0),
        most_common_intent: z.string().nullable().optional(),
    }).optional(),
    booking_patterns: z.object({
        by_day: z.record(z.string(), z.number()).optional(),
        by_hour: z.record(z.string(), z.number()).optional(),
        avg_party_size: z.number().default(0),
        most_booked_service: z.string().nullable().optional(),
    }).optional(),
    risk_assessment: z.object({
        level: z.enum(['low', 'medium', 'high']).default('low'),
        factors: z.array(z.string()).default([]),
    }).optional(),
    recommendations: z.array(z.object({
        type: z.string(),
        title: z.string(),
        description: z.string(),
    })).default([]),
});
